### ISSUE TITLE
Problem with $all_files definition + When media center is missing

### ISSUE THREAD

**Issue by slanglade** [darknebular/Wrapper_VideoStation#10]
Hi,

There's a problem with all_files variable definition. There's a missing '$' for the second path defined (vs_libsynovte_file.orig):

all_files=("$ms_libsynovte_file.orig" "$vs_libsynovte_file.orig" "/var/packages/CodecPack/target/bin/ffmpeg41.orig" "/var/packages/CodecPack/target/pack/bin/ffmpeg41.orig" "$ms_path/bin/ffmpeg.orig" "$vs_path/etc/TransProfile.orig" "$vs_path/bin/ffmpeg.orig")
firma="DkNbulDkNbul"

Another problem is when, like me, you don't have media center installed, only video station. Then the uninstaller fail to uninstall because inside uninstall() function, the "for" loop on $all_files is testing the first file, fails and then exits.

`
if [[ "$unmode" == "New" ]]; then
for losorig in "${all_files[@]}"; do
  if [[ -f "$losorig" ]]; then
...`

The test inside the for loop is strange : it only test the first occurence. It then either do all the uninstall stuff inside a single occurence of the loop and exit, or exits with an error message (the 17th). 

When the media center is not installed, this first file verification fails and everything stops. Can you modify the logic to test wether media center and/or video station is installed, and only do the part that is needed ?

Thanks a lot for your work, I'm now enjoying a lot more file format :-)

**Comment by darknebular** [comment]
First of all, the variable "all_files" is OK. because I must to comply with these two paths, because there are bad installers than install or try to install its wrappers in the incorrect path, for example, in DSM 7.1 the correct is: **/var/packages/CodecPack/target/pack/bin/** and in /var/packages/CodecPack/target/bin/ there are only links files. **This folder doesn´t exist until the AME license is loaded**. When you need to clean everything did it from others installers, you must to declare the two paths.

I tried without Media Server and the wrapper was successfully uninstalled. There is an [@] that matches each entry in the list to the "all_files" variable. The first entry doesn´t exist but there isn't any problem with it, It will clean or uninstall the rest.

I will check it out this in another NAS and I will publish my results.

**Comment by slanglade** [comment]
Hi,

Thanks for your answer. I will try to update the uninstall logic, later this week or this weekend.

By the way, was this script generated by some tool, or is it 'handmade'?

**Comment by darknebular** [comment]
It´s handmade.
I found a simple solution. I only need to verify if exits a file (this file must be exists always) in all cases, with advanced or simple one, with others etc.
I changed the conditional and now is working. If you can improve something, you are welcome to contribute to it.

Fixed in SCPT_2.5

There was a bug when you haven't Media Server Installed. It is fixed now.

Regards.
