### ISSUE TITLE
Transcoding is not working on DS218play in VideoStation

### ISSUE THREAD

**Issue by mieszk3** [darknebular/Wrapper_VideoStation#19]
After applying your script on my DS218play I cannot play anything with EAC3 or DTS on VideoStation on Chrome, Safari or in DSVideo app on my Android TV.
After clicking on Play button, all I see is a loading progress circle. The movie never starts to play.
I tried the simple wrapper also - the same thing.
Is there anything more I need to do to make it works?
DS218play is using ARM processor (Realtek RTD1296 SoC).
When I checked processes running after I click Play, for a moment (few seconds) I saw once `ffmpeg27` process only.
Do I need to set up something more?

**Comment by darknebular** [comment]
Hello,
This model is using gstreamer and not ffmpeg, I Think.

My Wrapper change /var/packages/CodecPack/target/pack/bin/ffmpeg41 and not /var/packages/CodecPack/target/pack/bin/ffmpeg27.

**Please could you send me the result of this command?**

`ls -la /var/packages/CodecPack/target/pack/bin/`


Regards.

**Comment by mieszk3** [comment]
Sure:
```
total 1092
drwxr-xr-x 2 root root   4096 May  2 21:25 .
drwxr-xr-x 6 root root   4096 May  2 09:44 ..
-rwxr-xr-x 1 root root 226040 Mar 24 03:21 ffmpeg27
-rwxr-xr-x 1 root root 250896 Mar 24 03:21 ffmpeg33-for-audio
-rwxr-xr-x 1 root root 250888 Mar 24 03:21 ffmpeg33-for-surveillance
-rwxr-xr-x 1 root root  16181 May  2 21:25 ffmpeg41
-rwxr-xr-x 1 root root 259024 Mar 24 03:21 ffmpeg41.orig
-rwxr-xr-x 1 root root  44176 Mar 24 03:21 gst-inspect-1.0
-rwxr-xr-x 1 root root  35688 Mar 24 03:21 gst-launch-1.0
-rwxr-xr-x 1 root root   6072 Mar 24 03:21 gst-plugin-scanner
```

**Comment by darknebular** [comment]
Your model is using GStreamer for transcoding, finally It looks like that jump to use ffmpeg27 and not ffmpeg41.

**Please can you send me this logs?**

`tail -n 200 -f /tmp/wrapper_ffmpeg.log`

I would like to test using my wrapper in ffmpeg27, I will give you instructions in order to try this.

Best regards.

**Comment by mieszk3** [comment]
Unfortunately:
```
root@DS218play:/# tail -n 200 -f /tmp/wrapper_ffmpeg.log
tail: cannot open '/tmp/wrapper_ffmpeg.log' for reading: No such file or directory
tail: no files remaining
```

**Comment by mieszk3** [comment]
@darknebular FYI - patch from AlexPresso is working on my DS218Play. That is because it also patches ffmpeg27. The only missing part is a combination of [DTS or EAC3 or TrueHD] + [HEVC] - it still doesn't work on GStreamer.

**Comment by darknebular** [comment]
The flow in Play systems is:

Binary of VideoStation --> binary of AME (gstreamer) --> AME's ffmpeg27

In a system without Play:
binary of VideoStation --> binary of AME (ffmpeg41)


My Wrapper change only ffmpeg41 and not ffmpeg27.

The Alex's one, change the ffmpeg binary from VideoStation Folder and then do a permanent link to all ffmpeg binaries of the AME folder. Due to this in your case is working.
ffmpeg27 doesn't exists in other systems (It's deprecated), ffmpeg33 is used for surveillance and audio station (It's not necessary patch it with DTS or EAC3 (movies doesn't use this binary 33))

**Please Could you uninstall the Alex's script try again with my Wrapper and do these commands?**

`mv -n /var/packages/CodecPack/target/pack/bin/ffmpeg27 /var/packages/CodecPack/target/pack/bin/ffmpeg27.orig`

`ln -s -f /var/packages/CodecPack/target/pack/bin/ffmpeg41 /var/packages/CodecPack/target/pack/bin/ffmpeg27`


Best regards.

**Comment by mieszk3** [comment]
I tried it and I can confirm it works. Movies now play with audio. BUT there is one small issue - efficiency. Using your wrapper/patch movies hang every few seconds (like loading/caching). I didn’t noticed that on Alex'es patch (maybe your version needs more processor’s power?)

**Comment by darknebular** [comment]
The Alex's wrapper is using a simplest wrapper. Using ffmpeg27 don't have GPU transcoding and yes my wrapper having 5.1 and two audio's streams need a better cpu or having a GPU available for ffmpeg.
You must install the simplest one (It's Alex folk). Please install the simplest one. this will change the ffmpeg41 and permanent link will still working.

Regards.

**Comment by mieszk3** [comment]
You are right, Simple Wrapper works OK, no hangs. Thx for a guidance and help!

**Comment by mieszk3** [comment]
@darknebular Are you able to add a fix for your script to cover DS218play case with ffmpeg27?

**Comment by darknebular** [comment]
> @darknebular Are you able to add a fix for your script to cover DS218play case with ffmpeg27?

Yes, I Will do a new version fixing a bug with the new ffmpeg's versions, and I Will add the ffmpeg27 for This play appliances.

BEST regards.

**Comment by darknebular** [comment]
Hello, just published the new version called SCPT_3.1

With this installer, you will be able to play movies with this kind of devices. Remember to install the SIMPLEST one for better performance in your case.

Best regards.
