### ISSUE TITLE
YOU HAVEN'T THE LICENCE LOADED in Advanced Media Extension package and HOW TO FIX IT

### ISSUE THREAD

**Issue by samllzhang** [darknebular/Wrapper_VideoStation#29]
ERROR: YOU HAVEN'T THE LICENCE LOADED in Advanced Media Extension package. Please, LOAD this licence and try again with the Installer.

I have installed and activated the Advanced Media Extension, but I still receive this error message

**Comment by samllzhang** [comment]
DSM7.2 6450 
Video Station 3.1.0-3153
ffmpeg 6.02
Advanced Media Extension 3.1.1-3005

**Comment by samllzhang** [comment]
Advanced Media Extension 3.1.0-3005

**Comment by darknebular** [comment]
Open Advance Media Extension and you must to see a green tick there...
If not, you must to load the license. In order to activate the license, you must to transcode something using VideoStation.
If you haven't a original Synology, you can try with the license crack for AME (It's not mandatory for have installing the Wrapper and This crack is in Beta release).


![image](https://github.com/darknebular/Wrapper_VideoStation/assets/82757922/94b61a23-e547-4fc4-8a6f-2b91bd94d1ee)


If you want to see if you have loaded and activated the license you can to check it out doing this:

`cat /usr/syno/etc/codec/activation.conf`

If this file doesn't exist is due you have this license loaded.

If Exists but there is a False and not True, you need to try to transcode something in order to activate it.


Best regards.

**Comment by darknebular** [comment]
@samllzhang Could you give us a feedback?

Regards.

**Comment by darknebular** [comment]
@samllzhang Can you confirm me if there is a True there in this file?
`cat /usr/syno/etc/codec/activation.conf`

Regards.
