### ISSUE TITLE
DSM 7.2.x not supported

### ISSUE THREAD

**Issue by philipplotnikov** [darknebular/Wrapper_VideoStation#49]
The latest version on Synology is DSM 7.2.1-69057 Update 4 with 7.2 not being supported (looking at the startup check code only 7.1 / 7.0 (and 8?) is supported.

Also, reference to the "Manual process" is not clear. what is the manual process?

Thanks.

**Comment by darknebular** [comment]
I did the manual process for those who used DSM 6.X. Since for me that version is deprecated and I do not support it.
This manual procedure has been removed from my website. You just have to use the installation script.

DSM 8 is supported, yes, any version above DSM 7.1 will install the Wrapper X-Advanced, including DSM 8.

DSM 7.2 Is fully supported, included Update 4. If you have another Wrapper or have had another Wrapper in the system, it may not work if you do not clean it well beforehand. You can only have one Wrapper installed.

What error does it show you?


Regards.

**Comment by philipplotnikov** [comment]
Hi, thank for your quick reply.

I'm running a Synology DS218, latest available update DSM 7.2.1-69057 Update 4.

when running the script it throws the following error:

```
\u001b[36m====================FFMPEG WRAPPER INSTALLER FOR DSM 7.0 and above by Dark Nebular.====================
\u001b[36m====================This Wrapper Installer is only avalaible for DSM 7.0 and above only====================


\u001b[33mFFMPEG (or GStreamer) WRAPPER INSTALLER version: SCPT_3.9.7

\u001b[32m	
==================== Wrapper for VideoStation and DLNA MediaServer for DTS, EAC3 and TrueHD with transcoding to AAC 5.1: ====================
Synology VideoStation and MediaServer ffmpeg wrapper with DTS, EAC3 and TrueHD support. 
It enables hardware transcoding from Synology's ffmpeg for video and transcoding DTS, HEVC, EAC3, AAC, True HD from the ffmpeg of the SynoCommunity. 

When the Wrapper FFmpeg needs to transcoding you will have 2 audio's streams from the SAME track:
- In DLNA MediaServer = [1) AAC 5.1 512kbps AND 2) MP3 2.0 256kbps.] (by default)
- In  VIDEO-STATION   = [1) MP3 2.0 256kbp  AND 2) AAC 5.1 512kbps.] (by default)*
*(For Chromecast or Google TV or other clients that don´t accept 5.1 AAC neither multi audio's stream support).

Now, You can change the 5.1 audio´s codec from AAC 512kbps to AC3 640kbps independently of its audio´s streams order in VIDEO-STATION and DLNA MediaServer 
using the Configurator TOOL embedded into the Installer. 
(AC3 is more compatible with legacy 5.1 devices).

Works fine the OffLine transcoding and the streaming of tipical extensions like: MKV, MP4, AVI... Works fine the thumbnails in VideoStation.
You will have full control of each Audio's codecs parameter using the Configuration TOOL for the Advanced Wrapper Mode. 
The only Wrapper of Internet with 5.1 AAC support and with a Configurator TOOL.

============================================================      ¡¡¡¡¡ENJOY!!!!!     ============================================================

\u001b[32m[2024-02-26 20:34:22] \u001b[31mERROR: \u001b[31mYour DSM Version  is NOT SUPPORTED using this Installer. Please use the MANUAL Procedure.
```

**Comment by ChrisMarriott38** [comment]
Not sure if it's related i'm novice.

I get this outcome and doesn't work i dont think?


This patcher enables Advanced Media Extensions 3.0 for you, without having to login account.
This enables the AAC and HEVC codecs and its license in the AME package, until DSM 7.2.
When you install this License crack, the Wrapper will be deleted and you must to re-install it again.
Note that in order to use this, you will have to use a valid SN (but doesn't have to login synology account with that SN).


DISCLAIMER: Use at your own risk, although it has been done to be as safe as possible, there could be errors. (Crack for XPenelogy and Synology without AME's license).

THIS IS THE LICENSE CRACK MENU, PLEASE CHOOSE YOUR SELECTION:

 ( P ) INSTALL the AME's License Crack
 ( U ) UNINSTALL the AME's License Crack

 ( Z ) RETURN to MAIN menu.

Do you want to install the crack for the AME license?P
[2024-02-27 11:44:48] INFO: /var/packages/CodecPack/target/usr/lib/libsynoame-license.so backup created as /var/packages/CodecPack/target/usr/lib/libsynoame-license.so.orig.
[2024-02-27 11:44:48] INFO: /usr/syno/etc/license/data/ame/offline_license.json backup created as /usr/syno/etc/license/data/ame/offline_license.json.orig.
cp: cannot stat '/usr/syno/etc/license/data/ame/offline_license.sig': No such file or directory
[2024-02-27 11:44:48] INFO: /usr/syno/etc/license/data/ame/offline_license.sig backup created as /usr/syno/etc/license/data/ame/offline_license.sig.orig.
[2024-02-27 11:44:48] INFO: Applying the patch.
/tmp/installer_OffLine.sh: line 881: [{"appType": 14, "appName": "ame", "follow": ["device"], "server_time": 1666000000, "registered_at": 1651000000, "expireTime": 0, "status": "valid", "firstActTime": 1651000001, "extension_gid": null, "licenseCode": "0", "duration": 1576800000, "attribute": {"codec": "hevc", "type": "free"}, "licenseContent": 1}, {"appType": 14, "appName": "ame", "follow": ["device"], "server_time": 1666000000, "registered_at": 1651000000, "expireTime": 0, "status": "valid", "firstActTime": 1651000001, "extension_gid": null, "licenseCode": "0", "duration": 1576800000, "attribute": {"codec": "aac", "type": "free"}, "licenseContent": 1}]: command not found
[2024-02-27 11:44:48] INFO: Checking whether patch is successful...
[2024-02-27 11:44:48] INFO: Patched but unsuccessful.

No idea if im doing something wrong

**Comment by darknebular** [comment]
No, the license crack in your case It's not necessary.
I will check the version checker fuction.

I will answer to you if I found something bad.

**Comment by darknebular** [comment]
This is my fuction:

function check_versions() {
# NO SE TRADUCE

# Contemplando la posibilidad de que las sucesivas versiones 0 de DSM 8 y futuras sigan con las variables correctas.
if [[ "$majorversion" -ge "8" ]]; then
  cp_path="/var/packages/CodecPack/target/pack"
  cp_bin_path="$cp_path/bin"
  injector="X-Advanced"
**elif [[ "$majorversion" -eq "7" && "$minorversion" -ge "1" ]]; then**
  cp_path="/var/packages/CodecPack/target/pack"
  cp_bin_path="$cp_path/bin"
  injector="X-Advanced"
elif [[ "$majorversion" -eq "7" && "$minorversion" -eq "0" ]]; then
  cp_path="/var/packages/CodecPack/target"
  cp_bin_path="$cp_path/bin"
  injector="0-Advanced"

else
error "Your DSM Version $dsm_version is NOT SUPPORTED using this Installer. Please use the MANUAL Procedure."
error "Your DSM Version $dsm_version is NOT SUPPORTED using this Installer. Please use the MANUAL Procedure." >> $logfile
exit 1
fi
}

As you can see, DSM 7.1 or above will be select this conditional. But I don't know why in your case doesn't take this condition.

**Comment by darknebular** [comment]
**Please send to me the result of these commands:**

`cat /etc.defaults/VERSION | grep majorversion | sed 's/majorversion=//' | tr -d '"')`

and this too:
`cat /etc.defaults/VERSION | grep minorversion | sed 's/minorversion=//' | tr -d '"')`

**Comment by ChrisMarriott38** [comment]
Do i just copy those commands in to Putty to the root? I'm not very technical linux

**Comment by ChrisMarriott38** [comment]
![image](https://github.com/darknebular/Wrapper_VideoStation/assets/142601601/2a6f4e0f-828d-4311-aa87-7e6d40d0e08f)

I included the ) on the first goes and i don't think it liked it. I tried with out and got two numbers back 7 then a 1

**Comment by ChrisMarriott38** [comment]
I don't know if it helps but these are the files i think i used originally.

tinycore-redpill.v0.9.4.9.img.gz
DSM_DS3622xs+_42218.pat

**Comment by philipplotnikov** [comment]
<img width="1152" alt="image" src="https://github.com/darknebular/Wrapper_VideoStation/assets/99631/14ce8882-e5e4-4777-8d16-4bdfa3648d12">

There is no /etc.defaults
<img width="937" alt="image" src="https://github.com/darknebular/Wrapper_VideoStation/assets/99631/962de753-b1ec-4501-90ac-f917660b72ec">

**Comment by philipplotnikov** [comment]
<img width="961" alt="image" src="https://github.com/darknebular/Wrapper_VideoStation/assets/99631/45014fb0-a221-4ab8-9c4f-5694b1a80c0a">

Its running 7.2 Update 4, nothing special.

**Comment by darknebular** [comment]
Please run these commands into the clish of the NAS, using SSH.

Thanks.

**Comment by ChrisMarriott38** [comment]
They were run using Putty via the IP address and login for the NAS - Not on the computer i was using to access? Does this help.

**Comment by philipplotnikov** [comment]
> Please run these commands into the clish of the NAS, using SSH. NOT in your system.
> 
> Thanks.

I'm logged into the NAS via SSH, this is not my laptop.

**Comment by darknebular** [comment]
**Please send to me the result of these commands:**

`cat /etc/VERSION | grep majorversion | sed 's/majorversion=//' | tr -d '"'`

and this too:
`cat /etc/VERSION | grep minorversion | sed 's/minorversion=//' | tr -d '"'`

**Comment by darknebular** [comment]
> tried with out and got two numbers back 7 then a 1

your problem It's not related with Philipplotnikov.

Please open AME and check if you can see the green tick there.

**Comment by darknebular** [comment]
> > Please run these commands into the clish of the NAS, using SSH. NOT in your system.
> > Thanks.
> 
> I'm logged into the NAS via SSH, this is not my laptop.

I am not sure about this, in synology exists "usr" folder not "Users", and where is .syno folder in your system?

**Comment by darknebular** [comment]
Please, [philipplotnikov](https://github.com/philipplotnikov),  run these commands into the clish of the NAS, using SSH. NOT in your system.

Thanks.

**Comment by darknebular** [comment]
@ChrisMarriott38 Please try again with the script, I found a little error in the variables of function patch_ame_license.

Best regards.

**Comment by ChrisMarriott38** [comment]
Currently trying to update DSM on the NAS as I saw you mentioned it works in a more recent version so i thought it might be worth a try!

**Comment by ChrisMarriott38** [comment]
Not sure if it's the error you found or the update i just did. But currently just updated to DSM 7.2.1-69057 Update 4.

Re-ran the script and got this outcome.
![image](https://github.com/darknebular/Wrapper_VideoStation/assets/142601601/f545ff24-7146-4f0f-9114-979e4c439dbc)

I did the P option and it said successful. 

Now i get to this!
![image](https://github.com/darknebular/Wrapper_VideoStation/assets/142601601/28497cfe-1ebd-4d49-8065-5a98931f030d)

**Comment by darknebular** [comment]
> as I saw you mentioned it works in a more recent version so i thought it might be worth a try!

In your case, there was a Typo in a variable of the license patch. Please try again, just change this typo in the function.

In the case of Philip I think that he isn't really into the clish of the nas.

Best Regards.

**Comment by ChrisMarriott38** [comment]
Just opened Surveillance station and it now shows the IP camera feed! Incredible!

**Comment by philipplotnikov** [comment]
> Please, [philipplotnikov](https://github.com/philipplotnikov), run these commands into the clish of the NAS, using SSH. NOT in your system.
> 
> Thanks.

Wow.... this is a first. I feel a complete n00b :). I was working in the wrong terminal....... omfg.

Please ignore my OP :)

Anyway, working now, going to test the install

**Comment by darknebular** [comment]
OK, please tell me if all It's working for you and then I will close this case.


Regards.

**Comment by ChrisMarriott38** [comment]
It's all working amazing here now - Very impressed! :)

**Comment by philipplotnikov** [comment]
Ok, so patch was installed successful. (Options I )

However the the audio is still lagging / skipping

Audio Format: E-AC-3 (Dolby Digital Plus)
  Audio Rate: 640 kb/s @ 6 channels
  Audio Lang: English

**Comment by philipplotnikov** [comment]
Checking the MD5 it does not match any of the one in code
![image](https://github.com/darknebular/Wrapper_VideoStation/assets/99631/7ff4844a-2bac-43a8-868b-870179dbf7c4)

<img width="698" alt="image" src="https://github.com/darknebular/Wrapper_VideoStation/assets/99631/54904c41-609b-423a-86e2-73f65fbd9364">

**Comment by philipplotnikov** [comment]
All good, managed to get it to work with some workaround. thanks for support.

**Comment by darknebular** [comment]
The license crack It's not for you, you have a Synology authentic.

You only need to install the Wrapper the Advanced or the Simplest one. The script should check that you have enough cores and should recommend one wrapper or another.
In your case I recommend that you stay with Simplest, it consumes less when transcoding to 2.0.


Best regards.
