### ISSUE TITLE
提示证书过期了  

### ISSUE THREAD

**Issue by only3601** [darknebular/Wrapper_VideoStation#59]
root@DS916plus:~# bash -c "$(curl "https://raw.githubusercontent.com/darknebular/Wrapper_VideoStation/main/installer.sh")" -- -s install
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
root@DS916plus:~# ^C

**Comment by darknebular** [comment]
That certificate depends on github, I do not manage it. It comes out correctly for me.

Your problem is that you are on a network with SSL Deep Inspection, and they are putting another certificate in between.

Talk to your internet provider or network manager so they don't do that to you.
Greetings.
